name: Build Docs
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    uses: reqstool/.github/.github/workflows/common-build-docs.yml@main
