name: Build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    uses: reqstool/.github/.github/workflows/typescript-lint.yml@ec64e2df249d8a923d56688e61409b51ea0ca1e0 # main 2026-05-19
  build:
    needs:
      - lint
    uses: reqstool/.github/.github/workflows/typescript-build.yml@ec64e2df249d8a923d56688e61409b51ea0ca1e0 # main 2026-05-19
