name: Check release

on:
  workflow_call:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: |
            echo "Tag must start with 'v'"
            exit 1
      - name: Check branch
        if: github.event.release.target_commitish != 'main'
        run: |
            echo "Release must be on main branch!"
            exit 1
