name: Check Semantic PR
permissions:
  contents: read
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  check:
    uses: reqstool/.github/.github/workflows/common-check-semantic-pr.yml@288632d3b2644a54a2b627f8956a1ed41941492d # main 2026-05-13
