name: Publish

on:
  release:
    types: [created]

jobs:
  check-release:
    uses: reqstool/.github/.github/workflows/common-check-release.yml@ec64e2df249d8a923d56688e61409b51ea0ca1e0 # main 2026-05-19
    with:
      version-format: semver
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs:
      - check-release
      - build
    permissions:
      id-token: write
    uses: reqstool/.github/.github/workflows/typescript-publish-to-npm.yml@ba71d8039faae3a22e7956f09b7dc63ddc94c8b0 # main 2026-05-20
