name: Publish

on:
  push:
    tags:
      - 'v*'
    

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/2-add-workflow-for-tesing-building-and-publishing-package'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Build project
        run: npm run build
