name: Renovate auto-approve

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  approve:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    uses: reqstool/.github/.github/workflows/renovate-approve.yml@main
