name: Validate Renovate config

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

permissions:
  contents: read
  packages: read

jobs:
  validate:
    uses: reqstool/.github/.github/workflows/common-validate-renovate.yml@a4203a58cec87861655512b6b277a859db385796 # 1.1.0
