name: Validate Renovate config

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

permissions:
  contents: read
  packages: read

jobs:
  validate:
    uses: reqstool/.github/.github/workflows/common-validate-renovate.yml@ef815eae0bca7160cdc714126cac73f76d638b39 # 1.0.0
