name: Verify

on:
  push:
    branches:
      - '**'   # all branches
  workflow_call:
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files
        run: ls -al

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check format
        run: npm run format

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build
